### ISSUE TITLE
Custom Items (example: banners with nbt tags)

### ISSUE THREAD

**Issue by DerLinkman** [itsnewtjam/newtShop-Issues#11]
Hello,

first of all nice plugin!
I have a plugin request:
Custom Items (example: Items with nbt tags for example a red banner with the mojang logo)

Greetings 
DerLinkman

**Comment by itsnewtjam** [comment]
I can definitely add banners in the next update. Are there any other special items you'd like to see added specifically?

**Comment by DerLinkman** [comment]
Not at the moment :D I had this idea after we created the admin shop on our server which has a city flag (banner) which has a specified design

**Comment by itsnewtjam** [comment]
I'll definitely have custom banners available for 2.0 then!

**Comment by DerLinkman** [comment]
Thanks a lot!
