### ISSUE TITLE
Lore in Items

### ISSUE THREAD

**Issue by JmmCardoso** [itsnewtjam/newtShop-Issues#12]
**Describe the bug**

The issue is that i want to appear in item in shop the Lore with the price buy/sell and to try doing this i went to config file of the section, and add mannually a Lore like the image screenshot, but the problem is that, when i buy the item, the Lore remains in the Item.

**To Reproduce**
1. Go to 'building_blocks.yml'
2. Add Lore after Sell:
3. See error

**Expected behavior**
I wanted to show the lore when the player is watching items to buy/sell but when they buy it dont appear anything.

**Screenshots**
![90727525_801659243655598_2923960507587100672_n](https://user-images.githubusercontent.com/62615266/77458015-6c52c400-6df5-11ea-9a64-48deadc94944.jpg)
![90582273_145776180131400_6178499807519178752_n](https://user-images.githubusercontent.com/62615266/77458027-71177800-6df5-11ea-95ed-56b845d96880.jpg)
![screen](https://user-images.githubusercontent.com/62615266/77458348-f6029180-6df5-11ea-85a6-d68bb921bb59.PNG)
![screen1](https://user-images.githubusercontent.com/62615266/77458518-382bd300-6df6-11ea-89d1-3fcb1bf046ad.PNG)

**Setup**
 - newtShop Version: minecraft 1.15.2

**Additional context**

**Comment by itsnewtjam** [comment]
As of now this is intended behavior, but shop-only lore is planned for the 2.0 update.

I'll also add an option to display prices on the lore like you're trying as I think that's just a cool idea :)
