### ISSUE TITLE
Bug Buy shop

### ISSUE THREAD

**Issue by rovirhood** [itsnewtjam/newtShop-Issues#13]
When you buy something and you have this item in your inventory the buying will only cost just the number of items do you have

Example
1. The player have 1 of iron
2. /shop and he tries to buy 64 of iron
3. the player just pay 1 iron ingot and not 64.

**Setup**
 - newtShop Version: 1.4
 - newtLib Version: 1.2.2
 - Spigot Version: 1.15.2

If you fix this bug will be the best adminshop plugin! thx for all!

**Comment by itsnewtjam** [comment]
Confirmed bug, will be fixed in 2.0 update
