### ISSUE TITLE
Generating item with NBT tags

### ISSUE THREAD

**Issue by Erik-HV** [itsnewtjam/newtShop-Issues#2]
It's possible to generate a shop with itens with NBT tags? My server is set to be an adventure mode only, with jobs and professions, and i want players to be able to buy the tools by using money on a shop.

**Comment by itsnewtjam** [comment]
Not possible currently, but I'll get started working on that for the 1.2.0 update, should have that out soon!

**Comment by itsnewtjam** [comment]
Added in 1.2.0, be sure to update newtLib as well.

Can now set the CanDestroy, CanPlaceOn, and Unbreakable tags with item options. More details [here](https://docs.newtjam.com/newtshop/category-files/#optional-fields).
