### ISSUE TITLE
Back to Categories Button Not Working

### ISSUE THREAD

**Issue by Cranum** [itsnewtjam/newtShop-Issues#20]
**Describe the bug**
When I click on the back to categories button for the category in slot 26, it closes the GUI and doesn't work

**Config File**
https://mcpaste.io/f80ff654fc0dc2f3

**Setup**
 - newtShop Version: 1.4.0
 - newtLib Version: 1.2.2
 - Spigot Version: 1.14.4

**Comment by itsnewtjam** [comment]
This only applies when a category is in slot 26?

**Comment by Cranum** [comment]
It seems to be yes, I have them in other slots are they are fine, all but that slot!

**Comment by itsnewtjam** [comment]
And I assume you've tried moving that one to other slots to see if it works elsewhere?

**Comment by Cranum** [comment]
I did do that then it was fine. I then tried it again now and it now appears it is only with this one category!

**Comment by itsnewtjam** [comment]
That's really odd, would you mind sending that category file so I can try and dig into what's going wrong?

**Comment by Cranum** [comment]
Yeh no problem. Here is the category file

`display-item: CHEST
name: Crates
color: GREEN
tab-label: crates
slot: 26
items:
  CLASSES:
    itemType: CUSTOM
    buy: 500000.0
    sell: 0.0
    shopTitle: Classes Crate
    stack:
      v: 1976
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Classes Crate Key
        lore:
        - §7Right-Click on a "§6Classes§7" crate
        - §7to win an item!
        enchants:
          DURABILITY: 1
  KITS:
    itemType: CUSTOM
    buy: 250000.0
    sell: 0.0
    shopTitle: Kit Crate
    stack:
      v: 1976
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §aKit Crate Key
        lore:
        - §7Right-Click on a "§aKit§7" crate
        - §7to win an item!
        enchants:
          DURABILITY: 1
  GKIT:
    itemType: CUSTOM
    buy: 250000.0
    sell: 0.0
    shopTitle: Gkit Crate
    stack:
      v: 1976
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §cGKit Crate Key
        lore:
        - §7Right-Click on a "§cGKit§7" crate
        - §7to win an item!
        enchants:
          DURABILITY: 1
  COMMANDS:
    itemType: CUSTOM
    buy: 50000.0
    sell: 0.0
    shopTitle: Commands Crate
    stack:
      v: 1976
      type: TRIPWIRE_HOOK
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §9Commands Crate Key
        lore:
        - §7Right-Click on a "§9Commands§7" crate
        - §7to win an item!
        enchants:
          DURABILITY: 1
`

**Comment by itsnewtjam** [comment]
Huh, weird, it seems like it's working okay on my end... not sure what would be causing that

**Comment by Cranum** [comment]
Neither do I? Do you want me to send you the config as well? Would that help?

**Comment by itsnewtjam** [comment]
If it's not too much trouble could you send me all the category files you're using? I'll try to completely emulate your setup and see if I can narrow down what exactly is happening

**Comment by Cranum** [comment]
Can I private message it to you in any way? Discord?

**Comment by itsnewtjam** [comment]
Sure, itsnewtjam#1337

**Comment by Cranum** [comment]
Thanks
