### ISSUE TITLE
Change name of an item?

### ISSUE THREAD

**Issue by Nidrux** [itsnewtjam/newtShop-Issues#21]
Is there a possible way to give the item a custom name?
I couldn't find a way to give items a custom name. I've looked at the documentation but can't figure it out.
For example,
items:
   SPAWNER:
      Name: "CUSTOM NAME" -> ?
      buy: 200000
      sell: 0

Thank you in advance for helping!
Kind regards,
Nidrux

**Comment by itsnewtjam** [comment]
In the current version you should be able to use `shopTitle: 'CUSTOM NAME'`. A bit confusing (apologies!) but the option will be made easier in the upcoming update.
