### ISSUE TITLE
Sell Discounts aren't being applied with /sell or /sellall or /sellinv commands.

### ISSUE THREAD

**Issue by ucrRichard** [itsnewtjam/newtShop-Issues#22]
**Describe the bug**
Setting sell discounts does not affect the price using /sell or /sellall or /sellinv

**To Reproduce**
1. Change permissions for the user (i used lp to temporarily modify user perms)
2. Let user type /sell or /sellall or /sellinv
3. Price is not updating to the new discount value.

**Expected behavior**
I expect the sell price to update to the new sell discount value.

**Screenshots**

**Setup**
 - newtShop Version: 1.4
 - newtLib Version: 
 - Spigot Version: Paper (Most Recent)

**Additional context**
I've been trying to make a "sellinventory coupon" that multiplies the price of all items by some value. I've worked out the permissions on that coupon so that console can run commands and then force the player to write "/sellinv" but I've noticed that the prices aren't adjusting even though I've hardcoded some of the permissions in.

This and a lot of other players have been complaining about buy/sell quantities changing if they're already holding certain items (but I've noticed you're already working on that). Any updates would be great, thanks for the awesome plugin!

**Comment by itsnewtjam** [comment]
Oops, that's definitely an oversight on my part! I'll have that fixed in 2.0, as well as the quantity issues.

**Comment by ucrRichard** [comment]
Looking forward to it, thanks!
