### ISSUE TITLE
2 Issues, help please 

### ISSUE THREAD

**Issue by timid2020** [itsnewtjam/newtShop-Issues#26]
I  do not know how to deny certain items from being sold on the shop, like blocks

Additionally, I added the newtshop.discount.sell.x permission to my prestige ranks, and it didn't enable a sell boost

**Comment by itsnewtjam** [comment]
As in have an item able to be bought but not sold?

Hm, what number did you set for x?

**Comment by timid2020** [comment]
Yes, I have both buy and sell price the same to prevent profit, would I just set sell price to 0?

**Comment by itsnewtjam** [comment]
Yep, setting either buy or sell prices to 0 will disable them!

**Comment by timid2020** [comment]
Awesome, thank you
Now for the second issue
That sell boost permission isn't working, I have it set to increase by 25 percent at each prestige and yet it doesn't change them

**Comment by itsnewtjam** [comment]
So `newtshop.discount.sell.25` then, and I assume you move to `newtshop.discount.sell.50` after that?

**Comment by timid2020** [comment]
Right yes, that's the process but it still does nothing

**Comment by itsnewtjam** [comment]
As in the permissions aren't registering at all or they're conflicting?

**Comment by timid2020** [comment]
Aren't registering at all

**Comment by itsnewtjam** [comment]
What newtShop, newtLib, and Spigot versions are you running? I'll fire up a server to see if I get the issue as well

**Comment by timid2020** [comment]
So it's paperspigot but it's 1.15.2 143

idk how to check the others

**Comment by itsnewtjam** [comment]
What permissions plugin are you using?

**Comment by timid2020** [comment]
GroupManager

**Comment by itsnewtjam** [comment]
Hm, I loaded up a test server using GroupManager and giving myself the discount permission seems to work... Would you mind sending me a copy of your groups?

**Comment by timid2020** [comment]
I have one of my prestige ranks
  Prestige2:
    default: false
    permissions:
      - newtshop.discount.sell.75
    inheritance: 
      - Peasant
    info:
      build: false
      prefix: '&6&lPrestige II&f '
      suffix: ''

**Comment by itsnewtjam** [comment]
So in testing I did notice that you'll want to deny any previous discount permissions, but outside of that adding the permission to a group seems to work on my end

**Comment by timid2020** [comment]
Can you explain what you mean? Deny any previous discount perms?

**Comment by itsnewtjam** [comment]
Yeah, if a group inherits any discount permissions from another group, you'll have to deny the inherited discounts so they don't override the new ones.

Or actually I see it's inheriting from Peasant, I'd assume Peasant doesn't have any discount permissions?

**Comment by timid2020** [comment]
Nope

**Comment by itsnewtjam** [comment]
Just as a last option could you check which version of newtShop you're running? You can check in the console or with the /shopinfo command

**Comment by timid2020** [comment]
1.4.0

**Comment by itsnewtjam** [comment]
I'm not sure then, dropping the group you provided into GroupManager behaves as it should on my end :/

**Comment by timid2020** [comment]
:/

**Comment by itsnewtjam** [comment]
If you'd like, I could try and hop on the server and investigate sometime today. Feel free to shoot me a message on Discord itsnewtjam#1337 or Twitter @ itsnewtjam with the details if that's something you'd want to do

**Comment by timid2020** [comment]
Very much so; I've added you
