### ISSUE TITLE
In-game Editor and item translating

### ISSUE THREAD

**Issue by kacperleague9** [itsnewtjam/newtShop-Issues#27]
**Is your feature request related to a problem? Please describe.**

It's not

**Describe the solution you'd like**

I want you to add in-game editor because i don't know any plugin which has it for 1.12.2. In-game editor should allow to add cosmetic items to the gui [like glass panes].

The second is item translating like in zShop. It allows to change name of item in gui [this feature is not that important]

**Additional context**

**Comment by itsnewtjam** [comment]
An in-game editor is planned for the future, but there's no specific plan as to when that will be added. 

As for changing the name of an item in the GUI, in the current version you should be able to accomplish this by adding the `shopTitle:` option to an item!

**Comment by kacperleague9** [comment]
Oh okay. Maybe you can make file gui editor before in-game gui?

**Comment by itsnewtjam** [comment]
Yeah, a web editor for category files is currently in the works!

**Comment by kacperleague9** [comment]
Awesome. Waiting for it :)
