### ISSUE TITLE
/Sell - Internal Error Occured

### ISSUE THREAD

**Issue by haynesey** [itsnewtjam/newtShop-Issues#28]
Hello,

Whenever i try to use the /sell command i get the error - An internal error occurred.

 - newtShop Version: 1..4.0
 - Spigot Version: 1.8.8

Logs Below

14.04 00:04:17 [Server] ERROR Unhandled exception executing command 'sell' in plugin newtShop v1.4.0
14.04 00:04:17 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sell' in plugin newtShop v1.4.0
14.04 00:04:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:469) [EssentialsX-2.17.1.0.jar:?]
14.04 00:04:17 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) [EssentialsX-2.17.1.0.jar:?]
14.04 00:04:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
14.04 00:04:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
14.04 00:04:17 [Server] INFO Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/bukkit/util/Consumer
14.04 00:04:17 [Server] INFO at com.newtjam.commands.Sell.onCommand(Sell.java:55) ~[?:?]
14.04 00:04:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
14.04 00:04:17 [Server] INFO ... 18 more
14.04 00:04:17 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/Consumer
14.04 00:04:17 [Server] INFO at com.newtjam.commands.Sell.onCommand(Sell.java:55) ~[?:?]
14.04 00:04:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]

**Comment by itsnewtjam** [comment]
Whoops, yeah that bug must've been sitting around for a while. Should be an easy fix for 2.0!
