### ISSUE TITLE
Buy and Sell texts are not customizable

### ISSUE THREAD

**Issue by PeterMa9621** [itsnewtjam/newtShop-Issues#32]
**Describe the bug**
It is actually not a bug I think. The picture below will show what I am talking about clearly.
![a](https://user-images.githubusercontent.com/26262538/79533616-89b23100-8035-11ea-9ee8-d784fb2bc699.jpg)
I cannot find these two texts (buy and sell) in the lang.yml. Could you please add them inside, thanks.

**To Reproduce**
1. Change languages in the file lang.yml
2. Open the default shop, you will see only buy/sell does not change.

**Expected behavior**
Chat and GUI messages are fully customizable.

**Setup**
 - newtShop Version: 2.0.0
 - newtLib Version: 1.5.0
 - Spigot Version: 1.15.2

**Comment by itsnewtjam** [comment]
Complete oversight on my part! I'll have those added in a small patch soon
