### ISSUE TITLE
Problem with setting the items in the last row of the category menu

### ISSUE THREAD

**Issue by ItzDidoko** [itsnewtjam/newtShop-Issues#33]
**Describe the bug**
When I try to set the item of the category in the slots of the last row, it returns me
[newtShop] Invalid slot for category <name>, skipping...

**To Reproduce**
1. Set the category slot to some of the slots in the last row
2. Reload the plugin

**Expected behavior**
To set the category item in some of the slots in the last row.

**Screenshots**
I don't think I need to provide screenshots, but if you say
**Setup**
 - newtShop Version: 2.0.0
 - newtLib Version: 1.5.0
 - Spigot Version: 1.15.2

**Comment by itsnewtjam** [comment]
Oh yep, looks like I forgot to change the slot validation after adding custom GUI sizes. Should have that fixed in a minor patch soon!
