### ISSUE TITLE
Console spam when using /shopreload

### ISSUE THREAD

**Issue by dustindinh** [itsnewtjam/newtShop-Issues#4]
https://pastebin.com/2ET0JKit
Plugin version: 1.3.1
Spigot version: 1.12.2

**Comment by itsnewtjam** [comment]
The bottom of that stacktrace is cut off, do you have the rest of it?

**Comment by dustindinh** [comment]
My bad! Full stacktrace here:
https://pastebin.com/muzqX6Ww

**Comment by itsnewtjam** [comment]
Oh! That's my bad, I accidentally left some debug code in v1.3.1. I'll remove that and post an update shortly.

**Comment by dustindinh** [comment]
If you are using discord then let me know and i can help you testing this plugin, im plant to using your plugin in my upcoming Server. That's good :D!

**Comment by itsnewtjam** [comment]
For sure, I'm on Discord at itsnewtjam#1337
