### ISSUE TITLE
Bookshelf not working

### ISSUE THREAD

**Issue by DatIsNiels** [itsnewtjam/newtShop-Issues#40]
Hi i have tried the folllowing

` BOOKSHELF:
    buy: 54
    sell: 18
    item:
      type: NORMAL
      material: BOOKSHELF`

But the bookshelf does not appear

**Comment by itsnewtjam** [comment]
Hm, do you get anything in console once you /shopreload?

**Comment by DatIsNiels** [comment]
Nope, nothing

**Comment by itsnewtjam** [comment]
Could you send over your category file so I can take a look?

**Comment by DatIsNiels** [comment]
[misc.zip](https://github.com/itsnewtjam/newtShop-Issues/files/4499754/misc.zip)

**Comment by itsnewtjam** [comment]
Do you by chance have an item with ID 'BOOKSHELF' in another category, maybe if you're still using the default buildingBlocks.yml?

**Comment by DatIsNiels** [comment]
Nope, i have checked the files and i am not using it

**Comment by itsnewtjam** [comment]
Ah I found it, looks like you have the FIREWORK_ROCKET below your BOOKSHELF indented too far, pushing that back fixed it on my end.

Also noticed there's an extra t at the end of the material for OAK_FENCE_GATE

**Comment by DatIsNiels** [comment]
Alright thanks for the help
