### ISSUE TITLE
Translate options for Blocks and Sell all command for sell all the posibbles items in inventory

### ISSUE THREAD

**Issue by gabriel262m** [itsnewtjam/newtShop-Issues#5]
Hello! Would it be possible to add an option to translate the items?

example:
id:
*Grass_block*
- display: Bloque de Pasto

This is Spanish but can be used for translate to all lenguages

And the command / sell all
sell all inventory items that have been set to sell.

like:
sell all inventory items:
- Grass_block: 15
when 15 is the price

-Stone: 18

This can be useful to replace many plugins and commands that do not work as one would like.
And hurries the sale of items, very useful in servers with mines.

Thank you for such a wonderful plugin: D!

I hope these ideas are possible someday.

**Comment by itsnewtjam** [comment]
You could use the 'shopTitle' item option to give items translated names, though I think I'll have to extend that for it to act how you'd like it to, I'll work on that.

There is the /sellall command, which sells all of the item you're holding, say you hold cactus and use /sellall, it would sell all the cactus in your inventory. Or do you mean a command that would sell every sellable item in your inventory? If so I can add that as well.

**Comment by gabriel262m** [comment]
Yeah! all the sellable items :D that could be nice for all type of game and replaces a lot of plugins.

**Comment by itsnewtjam** [comment]
Sounds good, I'll have that and the expanded 'shopTitle' option in an update soon!

**Comment by itsnewtjam** [comment]
v1.4.0 adds the /sellinv command to sell all sellable items in the inventory, and the 'shopTitle' item option has been expanded to better support other languages. Let me know if you need any further help!
