### ISSUE TITLE
Additional GUI Features

### ISSUE THREAD

**Issue by RageYT** [itsnewtjam/newtShop-Issues#6]
Here is a list of some additional GUI features that I feel would be beneficial to this plugin.
- A filler config option would be nice, meaning you can set one item in the config to fill all empty slots in the GUI with the selected item.
- Shop Title color code support, because why not?
- In-game editor to create/edit/add/delete categories without even having to touch the config.
- Proper item naming in the shopTitle and buy/sell messages, meaning no OAK_WOOD_PLANKS but instead Oak Planks
- Page variable to set the items page, so say I want a Diamond on page 2 and not automatically placed on whatever page, I can add `customPage: `
- Allow us to set a custom GUI size, for example 9, 18, etc.
- Have a variable such as **saleType: Sell/Buy/Both** to allow us to set the type of sale for a specific item, so I only want Diamonds to be sellable, I'll type **saleType: Sell** in the item's options.

**Comment by itsnewtjam** [comment]
- Easy enough, can have that in the 2.0 update
- Oof, oversight on my part, added in 2.0
- In-game editor is planned but a bit of a task, however a web-based editor is planned to be available with the 2.0 update
- Should be simple to address, expect in 2.0
- If I remember correctly it currently just works as basically `(pageNumber * pageSize) + slot`, but I can split that into two options in 2.0 if that's preferred?
- I can definitely look into custom GUI sizes
- You should already be able to accomplish this by setting a price you don't want available to 0, i.e. to disable selling, set `sellPrice: 0`
