### ISSUE TITLE
Items Missing When Adding customSlot: Value

### ISSUE THREAD

**Issue by RageYT** [itsnewtjam/newtShop-Issues#7]
**Describe the bug**
Items won't appear when all or most items in a category have the value **customSlot: **.

**To Reproduce**
1. In any config, add the value **customSlot: ** to every item in the category
2. Reload the plugin in-game
3. Visit the category and notice none of the items show

**Expected behavior**
Items are set in place and no items are missing from the category, regardless if they all have **customSlot: **

**Screenshots**
![image](https://user-images.githubusercontent.com/17907584/75078323-5343b400-54d3-11ea-94d3-c935be00106b.png)

**Setup**
 - newtShop Version: 1.4.0
 - newtLib Version: 1.2.2
 - Paper Version: [114](https://papermc.io/api/v1/paper/1.15.2/114/download)

**Additional information**
[Category Config](https://pastebin.com/abYCtYT0)

**Comment by itsnewtjam** [comment]
Confirmed bug, will be fixed in 2.0 update
