### ISSUE TITLE
Auto Sell Chests/Sell Wands/Container Selling

### ISSUE THREAD

**Issue by eevay** [itsnewtjam/newtShop-Issues#8]
**Is your feature request related to a problem? Please describe.**
Not particularly, however, it would be a much appreciated addition to the plugin as many container-selling plugins don't support this plugin's economy- making them incompatible.

**Describe the solution you'd like**
Auto Sell Chests - compatible with hoppers & act like a regular chest, but will automatically sell items to the shop- pretty op due to automation but very useful for inflated economy servers or just anyone who wants to have this feature

Sell Wands - an item (usually a golden hoe) that allows players to right click containers and automatically sell the contents- usually has configurable durability

Sell Signs - similar to how essentials has [Sell] and [Buy] signs, but would automatically sell the contents of a chest upon right clicking- would be easier than a buy wand, but not as quick or automated as a sell chest

**Additional context**
All of these could also be given custom sell multipliers (eg.  0.5 to make them sell all items for half the usual price). This could allow server owners to keep automation while somewhat nerfing it's use, allowing the playerbase to decide whether or not it is worth it to use the efficient methods despite lower sell rates.

This could also be used to make specific sell chests which maybe sell at a higher rate. These could be given limited uses, but would also have to be given individual sell rates rather than one global rate in the config file.

As for good examples; WildChests has sell chests as a feature. This plugin is alright, but lacks the support for your totally underrated shop plugin.

As for sell wands; there are a few plugins which do this. You can easily find them by simply searching for spigot sell wand plugins on google.

Hope this comes in handy and would love to see these implemented :)

Thanks

**Comment by itsnewtjam** [comment]
These are extremely interesting and cool ideas. Love the automation potential with them. I'll definitely look into adding them for 2.0!
